# -*- coding: utf-8 -*-
"""ACT 340.3.2 - Advanced String Exercise.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X-b8U2ZkM3dRD-VszrWANYIRYGgi9YJD

# String Excercises- Advanced

Complete the following practice excercises below to build up your skills with manipulating strings.

**Problem 1**

Create a new string with the following sentence:

“You learn more from failure than from success."
<br></br>
* Use the 1st, 4th, and last charachter to create a new string.
"""

string= "You learn more from failure than from success"

"""**Problem 2**

* Use the same string variable from above
* Use the replace() method to replace the "." with an "!"
"""

String=("You learn more from failure than from success")

"""**Problem 3**

*   Use the string variable below and create a new variable that has all of the charachters from the original string as lowercase charachters



"""

new_str= "“WHEN YOU Change your thougHts, remember to ALSO change your world.”"

"""**Problem 4**


*   Take the new_str variable from above and make all of charachters uppercase



"""

new_str="“when you Change your thoughts, remember to also change your world.”"

"""**Problem 5**

* Use the string variable below and the startswith() method to check and see if the string starts with the charachter "Z".
* Check if it starts with the charachter "t"

"""

new_str= "there are no traffic jams along the extra mile."

"""**Problem 6**



*   Use the same new_str variable and the index() method to identify the index of charachter "j"



"""

# prompt: Use the same new_str variable and the index() method to identify the index of charachter "j"

new_str= "there are no traffic jams along the extra mile."
try:
  index_of_j = new_str.index('j')
  print(f"The index of 'j' is: {index_of_j}")
except ValueError:
  print("The character 'j' is not found in the string.")

"""**Problem 7**

*   Use the same new_str variable
*   Use the count() method to find the number of times "t" and "o" appear in a string
* Create a print statement that has both results in one statement. You can use string concatenation, fstring, or any other way you can think of!


"""

a = new_str.count("t")
b = new_str.count("o")
print("The letter 't' appears {} times and the letter 'o' appears {} times.".format(a,b))

print(f"The letter 't' appears {a} times and the letter 'o' appears {b} times.")

"""**Problem 8**

* Using the string below, find the length of the given string.
"""

greeting= "Good Morning!"

"""**Problem 9**



*   Use the string below, and documentation on string methods to find if all the charachters in a string are alpha charachters.


"""

alphabet= "abcdefghijklmnopqrstuvwxyz"

"""**Problem 10**

Use the string below to complete the following:


*   Use the find() method for the value "y"
*   Use the index() method for the value "y"
*  Create a comment explaining the difference between the two methods




"""

learning= "Learning is fun!"

"""# Problem 11

Use the string below to count the number of times each charachter appears in a string.
"""

count_string= "Twinkle twinkle little star, how I wonder what you are"